version: '3'
services:
  backend:
    build:
      context: ./server
    container_name: reposcan_server
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./client
    container_name: reposcan_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
